CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    FOTO BLOB,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO_MUSICA VARCHAR(50),
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS ALBUMM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FOTO BLOB,
    QUANTIDADE_MUSICA VARCHAR,
    AVALIACAO INTEGER,
    FK_ID_ARTISTA INTEGER,
    FOREIGN KEY (FK_ID_ARTISTA) REFERENCES ARTISTA(ID) 
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR(2000) NOT NULL,
    DURACAO INTEGER NOT NULL,
    FOTO BLOB,
    FK_ID_ALBUM INTEGER NOT NULL,
    FK_ID_GENERO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID) ON DELETE CASCADE
);
