CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    CPF VARCHAR(15) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
    RG VARCHAR(20) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
    FOTO BLOB,
    CAUSA_DOR VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER PRIMARY KEY,
    DATA_CONSULTA DATE NOT NULL,
    NOME_MEDICO VARCHAR(255)NOT NULL,
    NOME_PACIENTE VARCHAR(255) NOT NULL,
    LOCAL VARCHAR(255) NOT NULL,
    FK_CRM_MEDICO VARCHAR(20),
    FK_CPF_PACIENTE VARCHAR(15),
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);
