CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU__AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO", "CASADO", "DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL", "MÉDIO", "SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENT_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
	PRIMARY KEY(ENQ_CODIGO),
	FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE (ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_DATANASC, USU_ESTADO_CIVIL, USU_EMAIL, USU_SENHA, USU_NOME, USU_ESTADO, USU_ESCOLARIDADE)
VALUES 				("2025-10-01","FerAmaral","2008-06-22","SOLTEIRO","fernanda@hotmail.com","12345678", "Fernanda Amaral", "SP", "MÉDIO"),
					("2025-10-01","Diego","2008-07-29","SOLTEIRO","diego@hotmail.com","45678", "Diego Viel", "SP", "MÉDIO"),
					("2025-10-01","Bruna","2008-10-26","SOLTEIRO","bruna@hotmail.com","8765", "Bruna Silva", "BA", "MÉDIO");
                    
INSERT INTO ENQUETE (ENT_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES 				("2025-01-09", "2025-09-09", "Descrição...", "Gabriel", 1),
					("2025-03-05","2025-10-15", "Descrição...", "Luis", 2),
					("2025-08-18", "2025-10-26", "Descrição...", "Ana", 2);
                    
INSERT INTO USUARIO_RESPONDE_ENQUETE(URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO )
VALUES 								("2025-01-09", 2, 1),
									("2025-03-05", 3, 2),
									("2025-08-18", 1, 2);
                    
INSERT INTO PERGUNTAS(PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES 				 ("O que é uma variável e para que ela serve em um programa?", 2),
					 ("Qual a diferença entre o comando while e o comando for em laços de repetição?", 3),
					 ("O que acontece se você esquecer de colocar uma condição de parada em um laço (while)?", 1);

INSERT INTO RESPOSTAS(RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES 				 ("Guarda valores na memória para usar no programa", "A", 7),
					 ("Repete enquanto a condição for verdadeira; for é usado quando já sabemos quantas vezes repetir", "B", 8),
					 ("Gera um loop infinito", "A", 9);
                     
SELECT 	*
FROM 	PERGUNTAS;