CREATE DATABASE IF NOT EXISTS BD_GESTAO_ESTOQUE;
USE BD_GESTAO_ESTOQUE;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR VARCHAR(50) NOT NULL,
    DATA_FABRICACAO DATE NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INTEGER,
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE
    );