CREATE DATABASE IF NOT EXISTS BD_BIBLIO_DIG;
USE BD_BIBLIO_DIG;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    FOTO BLOB,
    LIVROS_PUBLICADOS VARCHAR(255),
    GENERO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER PRIMARY KEY,
    NOME_LIVRO VARCHAR(255) NOT NULL,
    CATEGORIA VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(20) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL_LEITOR(
	ID INTEGER PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR(20),
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);

