CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF  NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO DATE NOT NULL,
    ESBOCO VARCHAR(255),
    DATA_ENTREGA DATE NOT NULL,
    QUANTIDADE INTEGER
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE INTEGER,
    PRAZO DATE NOT NULL,
    FK_ID_PROJETO INTEGER,
    FK_CPF_FUNCIONARIO VARCHAR(15),
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);