CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INTEGER
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER PRIMARY KEY,
    LUGAR_IDA VARCHAR(255) NOT NULL,
    LUGAR_DESTINO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER PRIMARY KEY,
    LOCALIDADE VARCHAR(10) NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR(15) NOT NULL,
    FK_ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE
);


